# Generated by Django 5.0.1 on 2024-01-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(default='', max_length=1000, verbose_name='Иконка')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('symbol', models.CharField(default='', max_length=10, verbose_name='Индекс')),
                ('price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='Включение/Выключение')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
            },
        ),
    ]
