# Generated by Django 5.0.1 on 2024-01-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_depositpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositpayment',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Включение/Выключение'),
        ),
    ]
