# Generated by Django 5.0.1 on 2024-01-25 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_depositpayment_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositpayment',
            name='reserve',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Резерв должен быть положительным')], verbose_name='Резерв'),
        ),
    ]
