# Generated by Django 5.0.1 on 2024-01-25 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_depositpayment_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositpayment',
            name='reserve',
            field=models.IntegerField(default=50000, validators=[django.core.validators.MinValueValidator(0, message='Резерв должен быть положительным')], verbose_name='Резерв'),
        ),
    ]
