# Generated by Django 5.0.1 on 2024-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_remove_depositpayment_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=100, verbose_name='')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10, verbose_name='min $')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, default=100000, max_digits=10, verbose_name='max $')),
            ],
            options={
                'verbose_name': 'Мин депозит',
                'verbose_name_plural': 'Мин депозит',
            },
        ),
    ]
