# Generated by Django 5.0.1 on 2024-01-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='address',
            new_name='wallet',
        ),
    ]
