# Generated by Django 5.0.1 on 2024-01-27 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_rename_address_exchange_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='sumFrom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='sumTo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='coinFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='coinTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.depositpayment'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='wallet',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
