# Generated by Django 5.0.1 on 2024-01-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_alter_exchange_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositpayment',
            name='qrcode',
            field=models.ImageField(upload_to='', verbose_name='QR-код для депозита'),
        ),
    ]
