# Generated by Django 5.0.1 on 2024-01-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_alter_depositpayment_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('P', 'Оплачено'), ('NP', 'Не оплачено')], default='NP', max_length=30, verbose_name='Статус'),
        ),
    ]
