# Generated by Django 5.0.1 on 2024-01-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_exchange_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('P', 'Оплачено'), ('NP', 'Не оплачено'), ('W', 'В ожидании')], default='W', max_length=30, verbose_name='Статус'),
        ),
    ]
