# Generated by Django 5.0.1 on 2024-01-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_alter_exchange_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
