# Generated by Django 5.0.1 on 2024-01-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0015_exchange_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositpayment',
            options={'verbose_name': 'Монета для депозитов', 'verbose_name_plural': 'Монеты для депозитов'},
        ),
        migrations.AlterModelOptions(
            name='depositsettings',
            options={'verbose_name': 'Min/Max депозит', 'verbose_name_plural': 'Min/Max депозит'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'verbose_name': 'Обмен', 'verbose_name_plural': 'Обмены'},
        ),
    ]
