# Generated by Django 5.0.1 on 2024-01-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0016_alter_depositpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='coinFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto', verbose_name='Из'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='coinTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.depositpayment', verbose_name='В'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sumFrom',
            field=models.CharField(max_length=100, null=True, verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sumTo',
            field=models.CharField(max_length=100, null=True, verbose_name='Продажа'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='wallet',
            field=models.CharField(max_length=500, null=True, verbose_name='Адресс'),
        ),
    ]
