# Generated by Django 5.0.1 on 2024-02-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0018_bank_alter_depositpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=2071614.45, max_digits=20, verbose_name='Резерв'),
        ),
        migrations.AlterField(
            model_name='depositsettings',
            name='crypto',
            field=models.CharField(max_length=20, null=True, verbose_name='Валюта'),
        ),
    ]
