# Generated by Django 5.0.1 on 2024-11-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0021_alter_bank_reserve_alter_depositsettings_crypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Изменить', editable=False, max_length=100, verbose_name='')),
                ('token', models.CharField(max_length=1000, verbose_name='Токен')),
                ('chat_id', models.CharField(max_length=1000, verbose_name='Чат ID')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Бот',
            },
        ),
        migrations.AlterField(
            model_name='bank',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=2572676.38, max_digits=20, verbose_name='Резерв'),
        ),
        migrations.AlterField(
            model_name='depositpayment',
            name='network',
            field=models.CharField(blank=True, choices=[('', ''), ('TRC-20', 'TRC-20'), ('BEP-20', 'BEP-20'), ('ERC-20', 'ERC-20'), ('C-Chain', 'C-Chain'), ('Polygon', 'Polygon')], default='', help_text='Указывать только на монеты где нужно', max_length=100, null=True, verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='depositsettings',
            name='crypto',
            field=models.CharField(max_length=20, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('W', 'В ожидании'), ('P', 'Оплачено'), ('NP', 'Ошибка'), ('S2', 'Шаг 2'), ('S3', 'Шаг 3')], default='W', max_length=30, verbose_name='Статус'),
        ),
    ]
