# Generated by Django 5.0.1 on 2024-11-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0022_tgbot_alter_bank_reserve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=1095981.23, max_digits=20, verbose_name='Резерв'),
        ),
        migrations.AlterField(
            model_name='depositsettings',
            name='crypto',
            field=models.CharField(choices=[('RUB', 'RUB')], max_length=20, null=True, verbose_name='Валюта'),
        ),
    ]
